/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Mario Caceres
 */
public class VistaEntrenador extends javax.swing.JFrame {

    /**
     * Creates new form VistaEntrenador
     */
    public VistaEntrenador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jL_nombre = new javax.swing.JLabel();
        jL_categoria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jL_Medallas = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Entrenador");

        jLabel2.setText("Nombe:");

        jLabel3.setText("Categoria:");

        jLabel4.setText("Medallas Obtenidas:");

        jL_nombre.setText("jLabel5");

        jL_categoria.setText("jLabel6");

        jScrollPane1.setViewportView(jL_Medallas);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pseudonimo", null, null, null, null, null, null},
                {"Especie", null, null, null, null, null, null},
                {"Nivel", null, null, null, null, null, null},
                {"Movimiento 1", null, null, null, null, null, null},
                {"Movimiento 2", null, null, null, null, null, null},
                {"Movimiento 3", null, null, null, null, null, null},
                {"Movimiento4", null, null, null, null, null, null}
            },
            new String [] {
                "", "Pokemon 1", "Pokemon 2", "Pokemon 3", "Pokemon 4", "Pokemon 5", "Pokemon 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jL_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(jL_categoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jL_nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jL_categoria)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEntrenador().setVisible(true);
            }
        });
    }
    
    public void setjL_categoria(String categoria){
        jL_categoria.setText(categoria);
    }
    public void setjL_nombre(String nombre){
        jL_nombre.setText(nombre);
    }
    public void setjTablePseudonimos(String[] pseudonimos){
        jTable1.setValueAt(pseudonimos[0], 0, 1);
        jTable1.setValueAt(pseudonimos[1], 0, 2);
        jTable1.setValueAt(pseudonimos[2], 0, 3);
        jTable1.setValueAt(pseudonimos[3], 0, 4);
        jTable1.setValueAt(pseudonimos[4], 0, 5);
        jTable1.setValueAt(pseudonimos[5], 0, 6);
    }
    public void setjTableNiveles(int[] niveles){
        jTable1.setValueAt(niveles[0], 2, 1);
        jTable1.setValueAt(niveles[1], 2, 2);
        jTable1.setValueAt(niveles[2], 2, 3);
        jTable1.setValueAt(niveles[3], 2, 4);
        jTable1.setValueAt(niveles[4], 2, 5);
        jTable1.setValueAt(niveles[5], 2, 6);
    }
    public void setjTableEspecies(String[] especies){
        jTable1.setValueAt(especies[0], 1, 1);
        jTable1.setValueAt(especies[1], 1, 2);
        jTable1.setValueAt(especies[2], 1, 3);
        jTable1.setValueAt(especies[3], 1, 4);
        jTable1.setValueAt(especies[4], 1, 5);
        jTable1.setValueAt(especies[5], 1, 6);
    }
    public void setjTableMovimiento1(String[] movimientos1){
        jTable1.setValueAt(movimientos1[0], 3, 1);
        jTable1.setValueAt(movimientos1[1], 3, 2);
        jTable1.setValueAt(movimientos1[2], 3, 3);
        jTable1.setValueAt(movimientos1[3], 3, 4);
        jTable1.setValueAt(movimientos1[4], 3, 5);
        jTable1.setValueAt(movimientos1[5], 3, 6);
    }
    public void setjTableMovimiento2(String[] movimientos2){
        jTable1.setValueAt(movimientos2[0], 4, 1);
        jTable1.setValueAt(movimientos2[1], 4, 2);
        jTable1.setValueAt(movimientos2[2], 4, 3);
        jTable1.setValueAt(movimientos2[3], 4, 4);
        jTable1.setValueAt(movimientos2[4], 4, 5);
        jTable1.setValueAt(movimientos2[5], 4, 6);
    }
    public void setjTableMovimiento3(String[] movimientos3){
        jTable1.setValueAt(movimientos3[0], 5, 1);
        jTable1.setValueAt(movimientos3[1], 5, 2);
        jTable1.setValueAt(movimientos3[2], 5, 3);
        jTable1.setValueAt(movimientos3[3], 5, 4);
        jTable1.setValueAt(movimientos3[4], 5, 5);
        jTable1.setValueAt(movimientos3[5], 5, 6);
    }
    public void setjTableMovimiento4(String[] movimientos4){
        jTable1.setValueAt(movimientos4[0], 6, 1);
        jTable1.setValueAt(movimientos4[1], 6, 2);
        jTable1.setValueAt(movimientos4[2], 6, 3);
        jTable1.setValueAt(movimientos4[3], 6, 4);
        jTable1.setValueAt(movimientos4[4], 6, 5);
        jTable1.setValueAt(movimientos4[5], 6, 6);
    }
    
    public void setJL_Medallas(ArrayList<String> valor){
       DefaultListModel modelo = new DefaultListModel();
       for (int i = 0; i < valor.size(); i++) {
          modelo.addElement(valor.get(i)); 
       }
       this.jL_Medallas.setModel(modelo);   
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jL_Medallas;
    private javax.swing.JLabel jL_categoria;
    private javax.swing.JLabel jL_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
