/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Mario Caceres
 */
public class VistaMedallas extends javax.swing.JFrame {

    /**
     * Creates new form VistaMedallas
     */
    public VistaMedallas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jL_Lider1 = new javax.swing.JLabel();
        jL_Lider2 = new javax.swing.JLabel();
        jL_Lider7 = new javax.swing.JLabel();
        jL_Lider4 = new javax.swing.JLabel();
        jL_Lider8 = new javax.swing.JLabel();
        jL_Lider6 = new javax.swing.JLabel();
        jL_Lider3 = new javax.swing.JLabel();
        jL_Lider5 = new javax.swing.JLabel();
        jL_tipo1 = new javax.swing.JLabel();
        jL_tipo2 = new javax.swing.JLabel();
        jL_tipo3 = new javax.swing.JLabel();
        jL_tipo4 = new javax.swing.JLabel();
        jL_tipo5 = new javax.swing.JLabel();
        jL_tipo6 = new javax.swing.JLabel();
        jL_tipo7 = new javax.swing.JLabel();
        jL_tipo8 = new javax.swing.JLabel();
        jL_posicion1 = new javax.swing.JLabel();
        jL_posicion2 = new javax.swing.JLabel();
        jL_posicion3 = new javax.swing.JLabel();
        jL_posicion4 = new javax.swing.JLabel();
        jL_posicion5 = new javax.swing.JLabel();
        jL_posicion6 = new javax.swing.JLabel();
        jL_posicion7 = new javax.swing.JLabel();
        jL_posicion8 = new javax.swing.JLabel();
        jB_combate = new javax.swing.JButton();
        jL_region = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Obtencion de Medallas");

        jL_Lider1.setText("Lider 1");

        jL_Lider2.setText("Lider 2");

        jL_Lider7.setText("Lider 7");

        jL_Lider4.setText("Lider 4");

        jL_Lider8.setText("Lider 8");

        jL_Lider6.setText("Lider 6");

        jL_Lider3.setText("Lider 3");

        jL_Lider5.setText("Lider 5");

        jL_tipo1.setText("jLabel10");

        jL_tipo2.setText("jLabel11");

        jL_tipo3.setText("jLabel12");

        jL_tipo4.setText("jLabel13");

        jL_tipo5.setText("jLabel14");

        jL_tipo6.setText("jLabel15");

        jL_tipo7.setText("jLabel16");

        jL_tipo8.setText("jLabel17");

        jL_posicion1.setText("jLabel18");

        jL_posicion2.setText("jLabel19");

        jL_posicion3.setText("jLabel20");

        jL_posicion4.setText("jLabel21");

        jL_posicion5.setText("jLabel22");

        jL_posicion6.setText("jLabel23");

        jL_posicion7.setText("jLabel24");

        jL_posicion8.setText("jLabel25");

        jB_combate.setText("Combatir!");

        jL_region.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_region.setText("Region");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jB_combate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(384, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_posicion1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jL_tipo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_Lider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_Lider2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jL_tipo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_posicion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_Lider3, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jL_tipo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_posicion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_Lider4, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jL_tipo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_posicion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_Lider5, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jL_tipo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_posicion5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_Lider6, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jL_tipo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_posicion6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_Lider7, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jL_tipo7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_posicion7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_Lider8, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jL_tipo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_posicion8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL_region, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_region)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Lider1)
                    .addComponent(jL_Lider2)
                    .addComponent(jL_Lider3)
                    .addComponent(jL_Lider4)
                    .addComponent(jL_Lider5)
                    .addComponent(jL_Lider6)
                    .addComponent(jL_Lider7)
                    .addComponent(jL_Lider8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_tipo1)
                    .addComponent(jL_tipo2)
                    .addComponent(jL_tipo3)
                    .addComponent(jL_tipo4)
                    .addComponent(jL_tipo5)
                    .addComponent(jL_tipo6)
                    .addComponent(jL_tipo7)
                    .addComponent(jL_tipo8))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_posicion1)
                    .addComponent(jL_posicion2)
                    .addComponent(jL_posicion3)
                    .addComponent(jL_posicion4)
                    .addComponent(jL_posicion5)
                    .addComponent(jL_posicion6)
                    .addComponent(jL_posicion7)
                    .addComponent(jL_posicion8))
                .addGap(18, 18, 18)
                .addComponent(jB_combate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMedallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMedallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMedallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMedallas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMedallas().setVisible(true);
            }
        });
    }
    
    public void setJL_lideres(String[] lideres){
        this.jL_Lider1.setText(lideres[0]);
        this.jL_Lider2.setText(lideres[1]);
        this.jL_Lider3.setText(lideres[2]);
        this.jL_Lider4.setText(lideres[3]);
        this.jL_Lider5.setText(lideres[4]);
        this.jL_Lider6.setText(lideres[5]);
        this.jL_Lider7.setText(lideres[6]);
        this.jL_Lider8.setText(lideres[7]);
    }
    
    public void setJL_region(String region){
        this.jL_region.setText(region);
    }
    
    public void setJL_tipos(String[] tipos){
        this.jL_tipo1.setText(tipos[0]);
        this.jL_tipo2.setText(tipos[1]);
        this.jL_tipo3.setText(tipos[2]);
        this.jL_tipo4.setText(tipos[3]);
        this.jL_tipo5.setText(tipos[4]);
        this.jL_tipo6.setText(tipos[5]);
        this.jL_tipo7.setText(tipos[6]);
        this.jL_tipo8.setText(tipos[7]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_combate;
    private javax.swing.JLabel jL_Lider1;
    private javax.swing.JLabel jL_Lider2;
    private javax.swing.JLabel jL_Lider3;
    private javax.swing.JLabel jL_Lider4;
    private javax.swing.JLabel jL_Lider5;
    private javax.swing.JLabel jL_Lider6;
    private javax.swing.JLabel jL_Lider7;
    private javax.swing.JLabel jL_Lider8;
    private javax.swing.JLabel jL_posicion1;
    private javax.swing.JLabel jL_posicion2;
    private javax.swing.JLabel jL_posicion3;
    private javax.swing.JLabel jL_posicion4;
    private javax.swing.JLabel jL_posicion5;
    private javax.swing.JLabel jL_posicion6;
    private javax.swing.JLabel jL_posicion7;
    private javax.swing.JLabel jL_posicion8;
    private javax.swing.JLabel jL_region;
    private javax.swing.JLabel jL_tipo1;
    private javax.swing.JLabel jL_tipo2;
    private javax.swing.JLabel jL_tipo3;
    private javax.swing.JLabel jL_tipo4;
    private javax.swing.JLabel jL_tipo5;
    private javax.swing.JLabel jL_tipo6;
    private javax.swing.JLabel jL_tipo7;
    private javax.swing.JLabel jL_tipo8;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
