/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Modelo.Pokemon;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Mario Caceres
 */
public class VistaEquipo extends javax.swing.JFrame {

    /**
     * Creates new form VistaEquipo
     */
    public VistaEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Pokemon1 = new javax.swing.JLabel();
        jL_Pokemon2 = new javax.swing.JLabel();
        jL_Pokemon3 = new javax.swing.JLabel();
        jL_Pokemon4 = new javax.swing.JLabel();
        jL_Pokemon5 = new javax.swing.JLabel();
        jB_Pokemon1 = new javax.swing.JButton();
        jB_Pokemon2 = new javax.swing.JButton();
        jB_Pokemon3 = new javax.swing.JButton();
        jB_Pokemon4 = new javax.swing.JButton();
        jB_Pokemon5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jL_Pokemon6 = new javax.swing.JLabel();
        jB_Pokemon6 = new javax.swing.JButton();
        jL_vida1 = new javax.swing.JLabel();
        jL_vida2 = new javax.swing.JLabel();
        jL_vida3 = new javax.swing.JLabel();
        jL_vida4 = new javax.swing.JLabel();
        jL_vida5 = new javax.swing.JLabel();
        jL_vida6 = new javax.swing.JLabel();
        jL_estado1 = new javax.swing.JLabel();
        jL_estado2 = new javax.swing.JLabel();
        jL_estado3 = new javax.swing.JLabel();
        jL_estado4 = new javax.swing.JLabel();
        jL_estado5 = new javax.swing.JLabel();
        jL_estado6 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_Pokemon1.setText("Pokémon 1");
        getContentPane().add(jL_Pokemon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 52, -1, -1));

        jL_Pokemon2.setText("Pokémon 2");
        getContentPane().add(jL_Pokemon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 94, -1, -1));

        jL_Pokemon3.setText("Pokémon 3");
        getContentPane().add(jL_Pokemon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 132, -1, -1));

        jL_Pokemon4.setText("Pokémon 4");
        getContentPane().add(jL_Pokemon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 176, -1, -1));

        jL_Pokemon5.setText("Pokémon 5");
        getContentPane().add(jL_Pokemon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 218, -1, -1));

        jB_Pokemon1.setText("Seleccionar");
        getContentPane().add(jB_Pokemon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 48, -1, -1));

        jB_Pokemon2.setText("Seleccionar");
        jB_Pokemon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Pokemon2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_Pokemon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jB_Pokemon3.setText("Seleccionar");
        getContentPane().add(jB_Pokemon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 131, -1, -1));

        jB_Pokemon4.setText("Seleccionar");
        getContentPane().add(jB_Pokemon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 172, -1, -1));

        jB_Pokemon5.setText("Seleccionar");
        getContentPane().add(jB_Pokemon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 214, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Selecionar Pokémon:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 11, -1, -1));

        jL_Pokemon6.setText("Pokémon 6");
        getContentPane().add(jL_Pokemon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 256, -1, -1));

        jB_Pokemon6.setText("Seleccionar");
        getContentPane().add(jB_Pokemon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 252, -1, -1));

        jL_vida1.setText("vida/vida");
        getContentPane().add(jL_vida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 52, -1, -1));

        jL_vida2.setText("vida/vida");
        getContentPane().add(jL_vida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 94, -1, -1));

        jL_vida3.setText("vida/vida");
        getContentPane().add(jL_vida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 132, -1, -1));

        jL_vida4.setText("vida/vida");
        getContentPane().add(jL_vida4, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 176, -1, -1));

        jL_vida5.setText("vida/vida");
        getContentPane().add(jL_vida5, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 218, -1, -1));

        jL_vida6.setText("vida/vida");
        getContentPane().add(jL_vida6, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 256, -1, -1));

        jL_estado1.setText("Estado");
        getContentPane().add(jL_estado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 52, -1, -1));

        jL_estado2.setText("Estado");
        getContentPane().add(jL_estado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 94, -1, -1));

        jL_estado3.setText("Estado");
        getContentPane().add(jL_estado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 132, -1, -1));

        jL_estado4.setText("Estado");
        getContentPane().add(jL_estado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 172, -1, -1));

        jL_estado5.setText("Estado");
        getContentPane().add(jL_estado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 218, -1, -1));

        jL_estado6.setText("Estado");
        getContentPane().add(jL_estado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 256, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_Pokemon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Pokemon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Pokemon2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEquipo().setVisible(true);
            }
        });
    }
    public void agregarListener(ActionListener al) {
       this.jB_Pokemon1.addActionListener(al);
       this.jB_Pokemon2.addActionListener(al);
       this.jB_Pokemon3.addActionListener(al);
       this.jB_Pokemon4.addActionListener(al);
       this.jB_Pokemon5.addActionListener(al);
       this.jB_Pokemon6.addActionListener(al);
       
    }
    public void setVistaCambio(Pokemon[] equipo, Pokemon activo, int index){
        this.setjL_Pokemon1(equipo[0].getPseudonimo());
        this.setjL_Pokemon2(equipo[1].getPseudonimo());
        this.setjL_Pokemon3(equipo[2].getPseudonimo());
        this.setjL_Pokemon4(equipo[3].getPseudonimo());
        this.setjL_Pokemon5(equipo[4].getPseudonimo());
        this.setjL_Pokemon6(equipo[5].getPseudonimo());
        if(equipo[0].getDebilitado()== true){
            this.setjL_estado1("Debilitado");
            jB_Pokemon1.setEnabled(false);
        }
        else{
            this.setjL_estado1("Disponible");
        }
        if(equipo[5].getDebilitado()== true){
            this.setjL_estado6("Debilitado");
            jB_Pokemon6.setEnabled(false);
        }
        else{
            this.setjL_estado6("Disponible");
        }
        if(equipo[1].getDebilitado()== true){
            this.setjL_estado2("Debilitado");
            jB_Pokemon2.setEnabled(false);
        }
        else{
            this.setjL_estado2("Disponible");
        }
        if(equipo[2].getDebilitado()== true){
            this.setjL_estado3("Debilitado");
            jB_Pokemon3.setEnabled(false);
        }
        else{
            this.setjL_estado3("Disponible");
        }
        if(equipo[3].getDebilitado()== true){
            this.setjL_estado4("Debilitado");
            jB_Pokemon4.setEnabled(false);
        }
        else{
            this.setjL_estado4("Disponible");
        }
        if(equipo[4].getDebilitado()== true){
            this.setjL_estado5("Debilitado");
            jB_Pokemon5.setEnabled(false);
        }
        else{
            this.setjL_estado5("Disponible");
        }
        if(index == 0){
            jB_Pokemon1.setEnabled(false);
        }
        if(index == 1){
            jB_Pokemon2.setEnabled(false);
        }
        if(index == 2){
            jB_Pokemon3.setEnabled(false);
        }
        if(index == 3){
            jB_Pokemon4.setEnabled(false);
        }
        if(index == 4){
            jB_Pokemon5.setEnabled(false);
        }
        if(index == 5){
            jB_Pokemon6.setEnabled(false);
        }
        this.setjL_vida1(equipo[0].getVida(), equipo[0].getVida_restante());
        this.setjL_vida2(equipo[1].getVida(), equipo[1].getVida_restante());
        this.setjL_vida3(equipo[2].getVida(), equipo[2].getVida_restante());
        this.setjL_vida4(equipo[3].getVida(), equipo[3].getVida_restante());
        this.setjL_vida5(equipo[4].getVida(), equipo[4].getVida_restante());
        this.setjL_vida6(equipo[5].getVida(), equipo[5].getVida_restante());
    }
    public void setjL_vida1(int vida, int restante){
        jL_vida1.setText(Integer.toString(restante)+" / "+Integer.toString(vida));
    }
    public void setjL_vida2(int vida, int restante){
        jL_vida2.setText(Integer.toString(restante)+" / "+Integer.toString(vida));
    }
    public void setjL_vida3(int vida, int restante){
        jL_vida3.setText(Integer.toString(restante)+" / "+Integer.toString(vida));
    }
    public void setjL_vida4(int vida, int restante){
        jL_vida4.setText(Integer.toString(restante)+" / "+Integer.toString(vida));
    }
    public void setjL_vida5(int vida, int restante){
        jL_vida5.setText(Integer.toString(restante)+" / "+Integer.toString(vida));
    }
    public void setjL_vida6(int vida, int restante){
        jL_vida6.setText(Integer.toString(restante)+" / "+Integer.toString(vida));
    }
    public void setjL_estado1(String estado){
        jL_estado1.setText(estado);
    }
    public void setjL_estado2(String estado){
        jL_estado2.setText(estado);
    }
    public void setjL_estado3(String estado){
        jL_estado3.setText(estado);
    }
    public void setjL_estado4(String estado){
        jL_estado4.setText(estado);
    }
    public void setjL_estado5(String estado){
        jL_estado5.setText(estado);
    }
    public void setjL_estado6(String estado){
        jL_estado6.setText(estado);
    }
    public void setjL_Pokemon1(String nombre){
        jL_Pokemon1.setText(nombre);
    }
    public void setjL_Pokemon2(String nombre){
        jL_Pokemon2.setText(nombre);
    }
    public void setjL_Pokemon3(String nombre){
        jL_Pokemon3.setText(nombre);
    }
    public void setjL_Pokemon4(String nombre){
        jL_Pokemon4.setText(nombre);
    }
    public void setjL_Pokemon5(String nombre){
        jL_Pokemon5.setText(nombre);
    }
    public void setjL_Pokemon6(String nombre){
        jL_Pokemon6.setText(nombre);
    }
    public JButton getBotonPokemon1(){
        return this.jB_Pokemon1;
    }
    public JButton getBotonPokemon2(){
        return this.jB_Pokemon2;
    }
    public JButton getBotonPokemon3(){
        return this.jB_Pokemon3;
    }
    public JButton getBotonPokemon4(){
        return this.jB_Pokemon4;
    }
    public JButton getBotonPokemon5(){
        return this.jB_Pokemon5;
    }
    public JButton getBotonPokemon6(){
        return this.jB_Pokemon6;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Pokemon1;
    private javax.swing.JButton jB_Pokemon2;
    private javax.swing.JButton jB_Pokemon3;
    private javax.swing.JButton jB_Pokemon4;
    private javax.swing.JButton jB_Pokemon5;
    private javax.swing.JButton jB_Pokemon6;
    private javax.swing.JLabel jL_Pokemon1;
    private javax.swing.JLabel jL_Pokemon2;
    private javax.swing.JLabel jL_Pokemon3;
    private javax.swing.JLabel jL_Pokemon4;
    private javax.swing.JLabel jL_Pokemon5;
    private javax.swing.JLabel jL_Pokemon6;
    private javax.swing.JLabel jL_estado1;
    private javax.swing.JLabel jL_estado2;
    private javax.swing.JLabel jL_estado3;
    private javax.swing.JLabel jL_estado4;
    private javax.swing.JLabel jL_estado5;
    private javax.swing.JLabel jL_estado6;
    private javax.swing.JLabel jL_vida1;
    private javax.swing.JLabel jL_vida2;
    private javax.swing.JLabel jL_vida3;
    private javax.swing.JLabel jL_vida4;
    private javax.swing.JLabel jL_vida5;
    private javax.swing.JLabel jL_vida6;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
